### ISSUE TITLE
Add some buttons to main page

### ISSUE THREAD

**Issue by mustafasakalli** [vaga/hugo-theme-m10c#48] opened 2020-07-29 12:20 UTC
Hello, I want to add "about", "topics", "contact" buttons to my home page, how can I achieve that?

**Comment by vaga** [comment] 2020-08-04 16:27
I'm working on it.

Duplicate of #47

**Comment by vaga** [comment] 2020-08-04 16:28
I'm working on it.

Duplicate of #37

**Comment by vaga** [comment] 2020-08-04 16:29
Duplicate of #37

**Closed** 2020-08-04 16:32 UTC
